name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy  # Job name must be exactly "deploy"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List repository contents
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Optional: List Docker Compose version to verify it's installed
      - name: Check docker-compose version
        run: docker-compose version

      # Build the images as defined in docker-compose.yml
      - name: Build Docker Images with docker-compose
        run: docker-compose build

      # Deploy using docker-compose
      - name: Deploy using docker-compose
        run: docker-compose up -d


