name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy  # Job name must be exactly "deploy"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List repository contents
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Optionally check the version of Docker Compose (v2)
      - name: Check Docker Compose Version
        run: docker compose version

      # Build the images using Docker Compose V2
      - name: Build Docker Images with docker compose
        run: docker compose build

      # Deploy using Docker Compose V2
      - name: Deploy using docker compose
        run: docker compose up -d

