name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy  # Job name must be exactly "deploy"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List repository contents
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: ${{ github.workspace }}
        run: |
          docker build -f Dockerfile -t fastapi-app .
      
      # Optionally, add a step to run the container (for testing/demo purposes)
      - name: Run Docker Container
        run: docker run -d -p 8000:8000 fastapi-app

