name: Deployment Pipeline

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy  # Job name must be exactly "deploy"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # (Optional) Set up Docker Buildx for advanced Docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t fastapi-app .

      # In this example, we simulate deployment by running the container.
      # Note: In a real deployment, you’d typically push your image to a registry
      # and deploy it to a production server (or use a container orchestration service).
      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 fastapi-app
